'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import VariantMatrix from './VariantMatrix';
import { useAdminHref } from '@/lib/admin-nav-context';
type Row = { variantId: string; productId: string; productName: string; sku: string; size: string; color: string; available: number; reserved: number; onHand: number; threshold: number; migrationRequired: boolean };
type Data = { items: Row[]; total: number; totalPages: number; products: { id: string; name: string }[]; sizes: string[]; colors: string[] };
export default function VariantStockView({ locationId }: { locationId: 'DEPOT' | 'BOUTIQUE' }) {
  const href = useAdminHref();
  const [configuring, setConfiguring] = useState<Row | null>(null);
  const [data, setData] = useState<Data>({ items: [], total: 0, totalPages: 0, products: [], sizes: [], colors: [] });
  const [filters, setFilters] = useState({ search: '', productId: '', size: '', color: '', status: '', sort: 'name' });
  const [page, setPage] = useState(1), [refresh, setRefresh] = useState(0), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Row | null>(null), [qty, setQty] = useState(''), [reason, setReason] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { const c = new AbortController(); const t = setTimeout(async () => { setLoading(true); try { const r = await fetch(`/api/admin/variant-stock?${new URLSearchParams({ ...filters, locationId, page: String(page) })}`, { signal: c.signal, cache: 'no-store' }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setData(d); setError(''); } catch (e) { if (!c.signal.aborted) setError(String(e)); } finally { if (!c.signal.aborted) setLoading(false); } }, 180); return () => { clearTimeout(t); c.abort(); }; }, [filters, page, locationId, refresh]);
  async function adjust() { if (!selected) return; setBusy(true); try { const r = await fetch('/api/admin/variant-stock/adjust', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ variantId: selected.variantId, locationId, qty: Number(qty), reason }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setSelected(null); setRefresh(v => v + 1); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  function filter(key: keyof typeof filters, value: string) { setFilters(f => ({ ...f, [key]: value })); setPage(1); }
  return <div className="p-4 sm:p-8"><header className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-black">Stock {locationId === 'DEPOT' ? 'Dépôt' : 'Boutique'}</h1><p className="mt-1 text-sm text-ink-500">{locationId === 'DEPOT' ? 'Disponibilité des commandes en ligne.' : 'Disponibilité de la caisse POS.'} Stock exact par taille et couleur.</p></div><div className="flex gap-2"><Link className="btn-ghost" href={href('/stocktakes')}>Inventaires</Link><Link className="btn-primary" href={href('/transfers')}>Transferts</Link></div></header>
    <div className="mb-5 flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><input aria-label="Rechercher" placeholder="Produit, SKU…" className="input w-56" value={filters.search} onChange={e => filter('search', e.target.value)} />{(['productId', 'size', 'color', 'status', 'sort'] as const).map(key => <select aria-label={key} className="input w-auto" key={key} value={filters[key]} onChange={e => filter(key, e.target.value)}>{(key === 'productId' ? [['', 'Tous les produits'], ...data.products.map(p => [p.id, p.name])] : key === 'size' ? [['', 'Toutes tailles'], ...data.sizes.map(s => [s, s])] : key === 'color' ? [['', 'Toutes couleurs'], ...data.colors.map(s => [s, s])] : key === 'status' ? [['', 'Tous les stocks'], ['in', 'En stock'], ['low', 'Stock faible'], ['out', 'Épuisé']] : [['name', 'Produit A-Z'], ['available', 'Disponible croissant']]).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select>)}</div>
    {error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
    <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-ink-100"><tr>{['Produit', 'Taille', 'Couleur', 'SKU', 'Disponible', 'Réservé', 'Stock', 'Actions'].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(r => <tr className="border-t" key={r.variantId}><td className="p-3 font-bold">{r.productName}{r.migrationRequired && <small className="block font-normal text-amber-700">Stock à répartir par taille et couleur</small>}</td><td className="p-3">{r.size || '—'}</td><td className="p-3">{r.color || '—'}</td><td className="p-3">{r.sku}</td><td className={`p-3 font-bold ${r.available <= 0 ? 'text-red-700' : r.available <= r.threshold ? 'text-amber-700' : 'text-emerald-700'}`}>{r.available} {r.available <= 0 ? '· Épuisé' : r.available <= r.threshold ? '· Faible' : ''}</td><td className="p-3">{r.reserved}</td><td className="p-3">{r.onHand}</td><td className="flex gap-2 p-3"><button className="btn-ghost text-xs" onClick={() => setConfiguring(r)}>{r.migrationRequired ? 'Configurer le stock' : 'Tailles / couleurs'}</button><button className="btn-ghost text-xs" onClick={() => { setSelected(r); setQty(''); setReason(''); }}>Ajuster</button><Link className="btn-ghost text-xs" href={href(`/stock-movements?variantId=${r.variantId}&locationId=${locationId}`)}>Mouvements</Link></td></tr>)}{!data.items.length && <tr><td colSpan={8} className="p-8 text-center">{loading ? 'Chargement…' : 'Aucune variante.'}</td></tr>}</tbody></table></div>
    <div className="mt-4 flex items-center justify-between text-sm"><span>{data.total} variantes · Page {page} / {Math.max(1, data.totalPages)}</span><div className="flex gap-2"><button className="btn-ghost" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Précédent</button><button className="btn-ghost" disabled={page >= data.totalPages} onClick={() => setPage(p => p + 1)}>Suivant</button></div></div>
    {configuring && <StockConfiguration product={configuring} onClose={() => { setConfiguring(null); setRefresh(v => v + 1); }} />}
    {selected && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-900/40 p-4"><section role="dialog" aria-modal="true" aria-label="Ajustement de stock" className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6"><h2 className="text-xl font-black">{selected.productName}</h2><p>{selected.size} / {selected.color} · {locationId}</p><label className="block text-sm">Quantité à ajouter (+) ou retirer (-)<input autoFocus type="number" step={1} className="input mt-1" value={qty} onChange={e => setQty(e.target.value)} /></label><label className="block text-sm">Motif obligatoire<input className="input mt-1" value={reason} onChange={e => setReason(e.target.value)} /></label>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button className="btn-ghost" disabled={busy} onClick={() => setSelected(null)}>Annuler</button><button className="btn-primary" disabled={busy || !Number.isInteger(Number(qty)) || !Number(qty) || !reason.trim()} onClick={adjust}>Enregistrer</button></div></section></div>}
  </div>;
}

function StockConfiguration({ product, onClose }: { product: Row; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => { dialog.current?.showModal(); }, []);
  return <dialog ref={dialog} onCancel={e => { if (saving) e.preventDefault(); else onClose(); }} className="fixed inset-0 m-auto max-h-[90dvh] w-[calc(100%_-_2rem)] max-w-3xl overflow-y-auto rounded-2xl border p-0 shadow-xl backdrop:bg-slate-900/40">
    <header className="sticky top-0 z-10 flex items-center justify-between gap-4 border-b bg-white p-4"><h2 className="text-xl font-black">{product.productName}</h2><button type="button" className="btn-ghost" disabled={saving} onClick={onClose}>Fermer</button></header>
    <div className="p-4 sm:p-6"><VariantMatrix key={product.productId} productId={product.productId} onBusyChange={setSaving} /></div>
  </dialog>;
}
